version: '3.8'

services:
  mongo:
    image: mongo
    container_name: ds-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    networks:
      - ds-network-prod

  backend:
    build:
      context: ./ds-backend
      dockerfile: Dockerfile
    container_name: ds-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./ds-backend/.env 
    volumes:
      - ./ds-backend/uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - ds-network-prod

  frontend:
    build:
      context: ./ds-frontend
      dockerfile: Dockerfile
    container_name: ds-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./ds-frontend/.env
    depends_on:
      - backend
    networks:
      - ds-network-prod

volumes:
  mongodb_data:
    driver: local

networks:
  ds-network-prod:
    driver: bridge
